exit if num nodes eq 0

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -22,6 +22,7 @@ runs:
             gcloud container clusters get-credentials colvin --region $GCP_REGION
         else
             gcloud container clusters get-credentials stage --zone $GCP_ZONE
+            if [ `kubectl get nodes -o json | jq '.items | length'` -eq 0 ]; then echo "ERROR: stage is stopped. Remember to start it!"; exit 1; fi
         fi
       shell: bash
 
@@ -37,7 +38,11 @@ runs:
             if [ -d "./terraform" ]; then terraform workspace select $STAGE terraform/ || terraform workspace new $STAGE terraform/; fi
         fi
       shell: bash
-
+      
+    - name: "Decrypt terraform encrypted values"
+      run: if [ -f "./terraform/variables-encrypted.tf.enc" ]; then sops -d terraform/variables-encrypted.tf.enc > terraform/variables-encrypted.tf; fi
+      shell: bash
+      
     - name: "Terraform Plan"
       run: if [ -d "./terraform" ]; then terraform plan -var="client_secret=`echo $SA_GCP`" -var="app_name=`echo $APP_NAME`" terraform/; fi
       shell: bash
